### ISSUE TITLE
writing TSV not working .. 

### ISSUE THREAD

**Issue by fbergmann** [derHahn/SBtab#19]
Hello, 

I've tried to use the following program: 

```
import libsbml
import sbml2sbtab   
import sys
import tablibIO

reader     = libsbml.SBMLReader()
sbml       = reader.readSBML(sys.argv[1])
A          = sbml2sbtab.SBMLDocument(sbml,sys.argv[1])
sbtabfiles = A.makeSBtabs()

for tab in sbtabfiles: 
  tab.createDataset()
  tab.writeSBtab('tsv', tab.table_name)
```

that failed miserably ... basically because the writeSBTab method was relying on the internal dataset being initialized. Now I'm not completely sure how the API is supposed to work, so I've hacked together the following patch: 

```
 scripts/SBtab.py | 10 ++++++----
 1 file changed, 6 insertions(+), 4 deletions(-)

diff --git a/scripts/SBtab.py b/scripts/SBtab.py
index d14d8d8..082b5ad 100755
--- a/scripts/SBtab.py
+++ b/scripts/SBtab.py
@@ -66,6 +66,8 @@ class SBtabTable():
 
         # Create all necessary variables
         self.initializeTable()
+        
+        self.sbtab_dataset = []
 
     def initializeTable(self):
         """
@@ -367,7 +369,7 @@ class SBtabTable():
         """
         # Initialize empty variables for conversion
         sbtab_temp = []
-        sbtab_dataset = tablib.Dataset()
+        self.sbtab_dataset = tablib.Dataset()
 
         # Create list of header
         header = self.header_row.split(' ')
@@ -400,11 +402,11 @@ class SBtabTable():
             if len(row) < longest:
                 for i in range(longest - len(row)):
                     row.append('')
-                sbtab_dataset.append(row)
+                self.sbtab_dataset.append(row)
             else:
-                sbtab_dataset.append(row)
+                self.sbtab_dataset.append(row)
 
-        return sbtab_dataset
+        return self.sbtab_dataset
 
     def addRow(self, row_list, position=None):
         """
```

**Comment by timolubitz** [comment]
This issue is closed. There were some minor bugs and one or two more severe things in the handling of the interface. Everything should be fine if one uses this code for the SBML to SBtab Conversion:

****************************************************************************************************
import libsbml
import sbml2sbtab   
import sys
import tablibIO
import SBtab

reader     = libsbml.SBMLReader()
sbml       = reader.readSBML(sys.argv[1])
model      = sbml.getModel()
A          = sbml2sbtab.SBMLDocument(model,sys.argv[1])
(sbtabfiles,warnings) = A.makeSBtabs()

for tab in sbtabfiles:
    tablib_tab = tablibIO.importSetNew(tab[0],sys.argv[1],seperator='\t')
    SBtab_obj  = SBtab.SBtabTable(tablib_tab,sys.argv[1])
    SBtab_obj.createDataset()
    SBtab_obj.writeSBtab('tsv', sys.argv[1]+'_'+tab[1])
****************************************************************************************************


Please wait for the commit, though, this will follow at latest by the end of the week.
